# Copyright (C) 2026 Lorenzo Orsini
# Author(s):
#   - Lorenzo Orsini, lorenzo.orsini3@gmail.com
#   - Alex Carnoli, alex.carnoli@gmail.com
# This file is part of CpG Island Predictor (CIP).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from modules.__init__ import __version__ as VERSION
if __name__ == "__main__":
    print(f"CpG Island Predictor (CIP) {VERSION}")

import json, sys, re, uuid, pathlib
import pandas as pd
import onnxruntime as rt
import numpy as np
from datetime import datetime
from urllib.parse import quote
from Bio import SeqIO
from colorama import Fore, deinit, init

try:
    from tqdm import tqdm
    _TQDM_AVAILABLE = True
except ImportError:
    _TQDM_AVAILABLE = False

from modules.features_extractor import FEATURES_ORDER, extract_features
from modules.exception_handler import _handle_error, _handle_warning
from modules.logger import _SCRIPT_DIR, log, wait_for_archiver

log.info("Session started, CIP %s", VERSION)

_MODEL_FILE        = _SCRIPT_DIR / "config" / "model.onnx"
_METADATA_FILE     = _SCRIPT_DIR / "config" / "metadata.json"
_OUTS_DIR          = _SCRIPT_DIR / "outs"
_SUPPORTED_FORMATS = {"bed", "gff3"}


def _load_metadata() -> dict | None:
    """Load metadata.json from config. Returns None if missing or unreadable."""
    try:
        with open(_METADATA_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        _handle_warning("warning", "metadata.json not found", log)
    except Exception as e:
        _handle_warning("warning", f"Could not read metadata.json: {e}", log)
    return None


def _parse_coords_from_header(header: str) -> tuple[str, int, int] | None:
    """Extract genomic coordinates from a FASTA header, if present.

    Matches common formats produced by bedtools/samtools, e.g.:
        chr1:10000-20000  or  chr1:10,000-20,000

    Returns a (chrom, start, end) tuple using 0-based half-open (BED)
    coordinates, or None if no coordinate pattern is found.
    """
    m = re.search(r"([\w.]+):(\d[\d,]*)-(\d[\d,]*)", header)
    if not m:
        return None
    chrom = m.group(1)
    start = int(m.group(2).replace(",", ""))
    end   = int(m.group(3).replace(",", ""))
    return chrom, start, end


def _write_bed(print_items: list[dict], output_path: pathlib.Path) -> bool:
    """Write predictions to a BED9 file.

    Coordinates come from the FASTA header when available (chr:start-end);
    otherwise the sequence id is used as chrom with coordinates spanning
    the full sequence length.

    Score field: int(probability × 1000), clamped to [0, 1000].
    Colour coding: green (0,200,0) = CpG island; red (200,0,0) = non-island.

    Returns True on success, False on I/O error.
    """
    lines = [
        'track name="CIP_predictions" '
        'description="CpG Island Predictor output" '
        'itemRgb="On"\n'
    ]
    for item in print_items:
        chrom = item.get("chrom", item["id"])
        start = item.get("coord_start", 0)
        end   = item.get("coord_end", item.get("seq_len", 0))
        score = min(int(item["proba"] * 1000), 1000) if item["proba"] is not None else 0
        rgb   = "0,200,0" if item["pred"] == 1 else "200,0,0"
        lines.append(
            f"{chrom}\t{start}\t{end}\t{item['id']}\t{score}\t"
            f".\t{start}\t{end}\t{rgb}\n"
        )
    try:
        output_path.write_text("".join(lines), encoding="utf-8")
        return True
    except Exception as e:
        print(_handle_error(e, output_path))
        return False


def _write_gff3(print_items: list[dict], output_path: pathlib.Path) -> bool:
    """Write predictions to a GFF3 file.

    Coordinates follow GFF3 convention (1-based, closed intervals).
    Feature type is ``CpG_island`` for positive predictions and
    ``non_CpG_island`` for negative ones. Probability and prediction flag
    are stored in the attributes column.

    Returns True on success, False on I/O error.
    """
    lines = [
        "##gff-version 3\n",
        f"# Generated by CIP {VERSION} on {datetime.now().isoformat(timespec='seconds')}\n",
    ]
    for item in print_items:
        chrom     = item.get("chrom", item["id"])
        gff_start = item.get("coord_start", 0) + 1   # GFF3 is 1-based
        gff_end   = item.get("coord_end", item.get("seq_len", 0))
        score_str = f"{item['proba']:.4f}" if item["proba"] is not None else "."
        feat_type = "CpG_island" if item["pred"] == 1 else "non_CpG_island"
        attrs = (
            f"ID={quote(str(item['id']), safe='')};"
            f"prediction={item['pred']};"
            f"probability={score_str}"
        )
        lines.append(
            f"{chrom}\tCIP\t{feat_type}\t{gff_start}\t{gff_end}\t"
            f"{score_str}\t.\t.\t{attrs}\n"
        )
    try:
        output_path.write_text("".join(lines), encoding="utf-8")
        return True
    except Exception as e:
        print(_handle_error(e, output_path))
        return False


def validate_fasta(fasta_file: str) -> bool:
    """Return True if ``fasta_file`` has a recognised FASTA extension."""
    valid_ext = {".fa", ".fasta", ".fna", ".ffn", ".faa", ".frn", ".txt"}
    if pathlib.Path(fasta_file).suffix.lower() not in valid_ext:
        _handle_warning(
            "warning",
            f"File format not supported for {fasta_file}. Please, use only "
            "'.fa', '.fasta' '.fna', '.ffn', '.faa', '.frn' or '.txt' extensions.",
            log,
        )
        return False
    return True


def predict_from_fasta(
    model,
    fasta_path: str,
    output_formats: set[str] | None = None,
) -> None:
    """Run predictions on all sequences in a FASTA file.

    One prediction is made per sequence using only sequence-based features
    (mono-, di- and trinucleotide counts). Results are always written to a
    CSV file; BED and GFF3 files are written when requested via
    ``output_formats``.

    Args:
        model:          A loaded ONNX InferenceSession.
        fasta_path:     Path to the input FASTA file.
        output_formats: Set of extra output formats (``"bed"``, ``"gff3"``).
    """
    if output_formats is None:
        output_formats = set()

    if not validate_fasta(fasta_path):
        return

    try:
        records = list(SeqIO.parse(fasta_path, "fasta"))
    except Exception as e:
        print(_handle_error(e, fasta_path))
        log.error("Failed to parse FASTA '%s': %s", fasta_path, e)
        return

    if not records:
        _handle_warning("warning", f"No sequences found in {fasta_path}", log)
        return

    log.info(
        "Run started — file: '%s', sequences: %d, formats: %s",
        fasta_path, len(records), output_formats or {"csv"},
    )

    output_rows = []
    print_items = []

    record_iter = (
        tqdm(records, desc="Predicting", unit="seq", ncols=80)
        if _TQDM_AVAILABLE else records
    )
    input_name = model.get_inputs()[0].name

    for rec in record_iter:
        seq = str(rec.seq).upper()

        if not set(seq).issubset({"A", "C", "G", "T", "N"}):
            _handle_warning(
                "warning",
                f"Sequence '{rec.id}' contains invalid characters. Please use only A, C, T, G or N.",
                log,
            )
            continue

        if len(seq) < 150:
            _handle_warning(
                "warning",
                f"Sequence '{rec.id}' is too short ({len(seq)} bp, minimum 150 bp). Skipping.",
                log,
            )
            continue

        feats = extract_features(seq)
        if feats is None:
            _handle_warning("warning", f"Skipping '{rec.id}' due to feature extraction error.", log)
            continue

        seq_len = sum(1 for ch in seq if ch in "ATCG")
        coords  = _parse_coords_from_header(rec.description)
        chrom, coord_start, coord_end = coords if coords else (rec.id, 0, seq_len)

        X_np = np.array([[feats[f] for f in FEATURES_ORDER]], dtype=np.float32)
        try:
            outputs = model.run(None, {input_name: X_np})
            pred    = int(outputs[0][0])
            proba   = float(outputs[1][0][1]) if len(outputs) > 1 else None
        except Exception as e:
            _handle_warning("warning", f"Inference failed for '{rec.id}': {e}", log)
            continue

        log.debug("Predicted '%s': label=%d, proba=%.4f", rec.id, pred, proba if proba is not None else -1)

        output_rows.append({
            "id":          rec.id,
            "prediction":  pred,
            "probability": f"{proba:.4f}" if proba is not None else "N/A",
        })
        print_items.append({
            "id":          rec.id,
            "pred":        pred,
            "proba":       proba,
            "seq_len":     seq_len,
            "chrom":       chrom,
            "coord_start": coord_start,
            "coord_end":   coord_end,
        })

    # ── Write outputs ─────────────────────────────────────────────────────────
    try:
        _OUTS_DIR.mkdir(exist_ok=True)
    except Exception as e:
        print(_handle_error(e, str(_OUTS_DIR)))
        return

    base_path    = _OUTS_DIR / f"{datetime.now().strftime('%Y%m%d')}_{uuid.uuid4().hex[:10]}"
    written_files = []

    csv_path = base_path.with_suffix(".csv")
    try:
        pd.DataFrame(output_rows).to_csv(csv_path, index=False)
        written_files.append(csv_path)
    except Exception as e:
        print(_handle_error(e, csv_path))

    if "bed" in output_formats:
        bed_path = base_path.with_suffix(".bed")
        if _write_bed(print_items, bed_path):
            written_files.append(bed_path)

    if "gff3" in output_formats:
        gff3_path = base_path.with_suffix(".gff3")
        if _write_gff3(print_items, gff3_path):
            written_files.append(gff3_path)

    # ── Terminal output ───────────────────────────────────────────────────────
    for item in print_items:
        prob_str = f"{item['proba']:.4f}" if item["proba"] is not None else "N/A"
        if item["pred"] == 1:
            label = f"{Fore.LIGHTGREEN_EX}Sequence '{item['id']}' is a CpG island.{Fore.RESET}"
        else:
            label = f"{Fore.LIGHTRED_EX}Sequence '{item['id']}' is not a CpG island.{Fore.RESET}"
        print(f"- {label}\n\tProbability of CpG island: {prob_str}")

    print("\n    Results saved to:")
    for path in written_files:
        print(f"      {path}")
    log.info("Run complete — written: %s", written_files)


def _parse_version(v: str) -> tuple[int, ...]:
    """Parse a 'X.Y.Z' version string into a comparable tuple of ints."""
    try:
        return tuple(int(x) for x in v.lstrip("v").split("."))
    except ValueError:
        return (0,)


def _check_version_compatibility(metadata: dict) -> bool:
    """Check the running script version against the model's declared range.

    Fields read from metadata (both optional):
        min_script_version : str  – oldest compatible script version.
        max_script_version : str  – newest tested script version.

    Returns True if a fatal incompatibility is detected (script too old),
    False otherwise. A warning is printed when the script is newer than
    what was tested.
    """
    script_ver  = _parse_version(VERSION)
    min_ver_str = metadata.get("min_script_version")
    max_ver_str = metadata.get("max_script_version")

    if min_ver_str and script_ver < _parse_version(min_ver_str):
        _handle_warning(
            "error",
            f"This script is {VERSION} but the loaded model requires at least script "
            f"{min_ver_str}. Please update CIP.py.",
            log,
        )
        return True

    if max_ver_str and script_ver > _parse_version(max_ver_str):
        _handle_warning(
            "warning",
            f"This script is {VERSION} but the loaded model was "
            f"tested up to script {max_ver_str}. Results may differ from expected.",
            log,
        )

    return False


def _exit(code: int = 0) -> None:
    """Clean up colorama, wait for log archiver, then exit."""
    log.info("Session ended.\n")
    deinit()
    try:
        wait_for_archiver()
    except Exception as e:
        _handle_warning('error', f'Compression error: {e}')
        sys.exit(code)
    sys.exit(code)


if __name__ == "__main__":
    init()
    print(Fore.LIGHTBLACK_EX + "Copyright: AGPL-3.0-or-later (see LICENSE file)")
    print("See https://github.com/lorenzoorsini3/CpG-Island-Predictor for source code" + Fore.RESET)

    if not _TQDM_AVAILABLE:
        print("    Note: install 'tqdm' for progress bars (pip install tqdm).")

    # ── Load metadata ─────────────────────────────────────────────────────────
    metadata   = _load_metadata()
    n_features = None

    if metadata is not None:
        arch_version  = metadata.get("architecture_version", "unknown")
        n_features    = metadata.get("n_features")
        train_species = metadata.get("training_species", [])
        test_species  = metadata.get("test_species", [])
        print(f"    Model architecture : {arch_version}")
        if train_species:
            print(f"    Trained on         : {', '.join(train_species)}")
        if test_species:
            print(f"    Evaluated on       : {', '.join(test_species)}")
        log.info("Architecture: %s, trained on: %s", arch_version, train_species)
    else:
        _handle_warning("warning", "Metadata not found, proceeding without model info.", log)

    # ── Version compatibility check ───────────────────────────────────────────
    if metadata is not None and _check_version_compatibility(metadata):
        _exit(1)

    # ── Load model ────────────────────────────────────────────────────────────
    try:
        model = rt.InferenceSession(_MODEL_FILE)
    except Exception as e:
        print(_handle_error(e, _MODEL_FILE))
        log.error("Failed to load model '%s': %s", _MODEL_FILE, e)
        _exit(1)

    if n_features is not None and len(FEATURES_ORDER) != n_features:
        _handle_warning(
            "warning",
            f"Metadata expects {n_features} features but this version of CIP would build "
            f"{len(FEATURES_ORDER)}. Results may be unreliable.",
            log,
        )

    # ── Main loop ─────────────────────────────────────────────────────────────
    while True:
        try:
            raw = input("\nEnter FASTA path [--bed] [--gff3] or /quit: ").strip()
        except (KeyboardInterrupt, EOFError):
            print()
            _exit()

        if not raw:
            continue

        parts          = raw.split()
        fasta_path     = parts[0]
        flags          = {p.lstrip("-").lower() for p in parts[1:]}
        output_formats = flags & _SUPPORTED_FORMATS

        unknown_flags = flags - _SUPPORTED_FORMATS
        if unknown_flags:
            _handle_warning(
                "warning",
                f"Unrecognised flags ignored: {', '.join('--' + f for f in unknown_flags)}",
                log,
            )

        if fasta_path == "/quit":
            _exit()
        else:
            predict_from_fasta(model, fasta_path, output_formats)
